### ISSUE TITLE
Catmandu::Validator::JSONSchema uses  JSON::Validator internal data instead of public methods

### ISSUE THREAD

**Issue by phochste** [LibreCat/Catmandu-Validator-JSONSchema#4]
To read data out of the error messages of  JSON::Validator internal HASH keys are used and not the documented  JSON::Validator::Error methods. This brakes the code in  JSON::Validator 3.15 which has a different internal HASH but still supports the documented methods.

**Comment by nicolasfranck** [comment]
See https://github.com/LibreCat/Catmandu-Validator-JSONSchema/commit/4cc3cfae8df835599020614b22e671adc7ddc1c7

version 0.12 is not the way. Thanks for spotting this.
